### PR TITLE
52 bugfix email validation Druzhytskii

### PR DESCRIPTION
**Pull request by AndriiDruzhytskyi**
How test:
-Open login form.
-Press login button with empty email field.
-Expected result: warning "Email cannot be empty!".

-Enter some incorrect info to email field.
-Press login button again.
-Expected result: warning "Wrong email format!".

-Enter correct info to email field.
-Press login button again.
-Expected result: successful login.

### CODE REVIEW

**Comment by katemalash** [comment]
It's not good practice to separate Error messages for the cases of the incorrect login and incorrect password. It helps to break the application. It would be better to show Error message "Login or password is incorrect. Plese, try again" in all cases.

**Review by Dmitry528 — COMMENTED** [review]
1) I agree with Kate, use 
if (!pattern.test(this.email) || (!pattern.test(this.password))) -> error message
2) And change your message "Can`t find user with this email and password.", on "Incorrect login or password"

**Comment by AndriiDruzhytskyi** [comment]
> It's not good practice to separate Error messages for the cases of the incorrect login and incorrect password. It helps to break the application. It would be better to show Error message "Login or password is incorrect. Plese, try again" in all cases.

Ok, that's why I can't see the correct error message in other applications, and I have to keep guessing which field is wrong. Then we need a another task which will provide user possibility to check entered password field.

**Comment by AndriiDruzhytskyi** [comment]
> 1. I agree with Kate, use
>    if (!pattern.test(this.email) || (!pattern.test(this.password))) -> error message
> 2. And change your message "Can`t find user with this email and password.", on "Incorrect login or password"

Fixed. Please check before approve.

**Review by andrii-kondratiuk — APPROVED** [review]

**Review by Dmitry528 — APPROVED** [review]
Good work

**Review by marrybbb — APPROVED** [review]

**Pull request merged**
