### PR TITLE
28 feature create moderatros basiuk

### PR DESCRIPTION
**Pull request by DMTRIP**

### CODE REVIEW

**Review by Viktor-Hordynskyi — COMMENTED** [review]
Screenshot_2
pls, fix all of the errors (red borders)
1) all of my emails are wrong
2) error to the email address, is broken
3) moderator nickname is broken too

make your page a bit prettier, it looks very bad (blue borders)
1) your error message must be on one line (vertical) with the field
2) move your "create" button to center and bottom
3) center your text "something has go..."

**Comment by DMTRIP** [comment]
> Screenshot_2
> pls, fix all of the errors (red borders)
> 
> 1. all of my emails are wrong
> 2. error to the email address, is broken
> 3. moderator nickname is broken too
> 
> make your page a bit prettier, it looks very bad (blue borders)
> 
> 1. your error message must be on one line (vertical) with the field
> 2. move your "create" button to center and bottom
> 3. center your text "something has go..."

Done

**Comment by Viktor-Hordynskyi** [comment]
Screenshot_4
after your changes I can't to login to the admin panel - need to fix this

**Comment by DMTRIP** [comment]
> Screenshot_4
> after your changes I can't to login to the admin panel - need to fix this

mee too) lol

**Comment by Viktor-Hordynskyi** [comment]
You still have not solved the problem, I can't log in to the admin panel.

**Review by Dmitry528 — COMMENTED** [review]
1) Resolve conflicts
2) Return post method in service like in our current DEV

**Pull request closed without merging**
